name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        run: npm audit --json > npm-audit.json || true
        
      - name: Run ESLint
        run: npm run lint || true
        
      - name: Run tests with coverage
        run: npm test
        
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: Practice-10
          SONAR_PROJECT_NAME: Practice-10
          SONAR_PROJECT_VERSION: 1.1
          SONAR_SOURCES: src
          SONAR_TESTS: src/test
          SONAR_TEST_INCLUSIONS: src/test/**/*
          SONAR_JAVASCRIPT_LCOV_REPORTPATHS: coverage/lcov.info
          SONAR_COVERAGE_EXCLUSIONS: "src/test/**,**/__tests__/**"
          SONAR_EXCLUSIONS: "node_modules/**,**/node_modules/**,**/*.min.js,**/*.bundle.js,src/test/**"
          SONAR_SOURCE_ENCODING: UTF-8
          # Code smell detection settings
          SONAR_JAVASCRIPT_DUPLICATED_LINES_DENSITY_MINIMUM: 3
          SONAR_JAVASCRIPT_COMPLEXITY_FUNCTION_THRESHOLD: 15
          SONAR_JAVASCRIPT_COMPLEXITY_CLASS_THRESHOLD: 50
          SONAR_JAVASCRIPT_COMPLEXITY_FILE_THRESHOLD: 100
          SONAR_JAVASCRIPT_MAXSTATEMENTS_FUNCTION: 50
          SONAR_JAVASCRIPT_MAXSTATEMENTS_FILE: 200
          SONAR_JAVASCRIPT_MAXPARAMETERS_FUNCTION: 5
          SONAR_JAVASCRIPT_MAXNESTING_FUNCTION: 4
          SONAR_JAVASCRIPT_MAXLINES_FUNCTION: 50
          SONAR_JAVASCRIPT_MAXLINES_FILE: 500
          # ESLint integration
          SONAR_ESLINT_REPORT_PATHS: eslint-report.json
          SONAR_JAVASCRIPT_ESLINT_REPORT_PATHS: eslint-report.json
          # Security and vulnerability settings
          SONAR_SECURITY_HOTSPOTS_ENABLED: true
          SONAR_SECURITY_HOTSPOTS_REPORT_PATHS: npm-audit.json
          SONAR_SECURITY_HOTSPOTS_SEVERITY: critical,high,medium
          SONAR_SECURITY_HOTSPOTS_TAGS: security,vulnerability
          # Additional SonarQube settings
          SONAR_ANALYSIS_MODE: preview
          SONAR_ISSUE_ASSIGNEE: false
          SONAR_ISSUE_SEVERITY: info
          SONAR_ISSUE_TYPE: code_smell
          SONAR_ISSUE_EFFORT: 5
          SONAR_ISSUE_TAGS: maintainability,readability,complexity
          # Quality Profile settings
          SONAR_QUALITYGATE_WAIT: true
          SONAR_QUALITYGATE_CONDITIONS: coverage,duplicated_lines_density,code_smells,security_hotspots